# Generated by Django 6.0.3 on 2026-08-14 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muted_categories', models.JSONField(blank=True, default=list)),
                ('push_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('GRADES', 'Grades'), ('HOMEWORK', 'Homework'), ('CLASSROOM', 'Classroom'), ('EXAMS', 'Exams'), ('SUPPORT', 'Support'), ('REWARDS', 'Rewards & Shop'), ('SYSTEM', 'System')], db_index=True, default='SYSTEM', max_length=16)),
                ('event', models.CharField(choices=[('HOMEWORK_GRADED', 'Homework Graded'), ('MIDTERM_RESULT', 'Midterm Result'), ('CERTIFICATE_READY', 'Certificate Ready'), ('HOMEWORK_ASSIGNED', 'Homework Assigned'), ('HOMEWORK_DUE_SOON', 'Homework Due Soon'), ('MIDTERM_SCHEDULED', 'Midterm Scheduled'), ('CLASS_ANNOUNCEMENT', 'Class Announcement'), ('COMMENT_REPLY', 'Comment Reply'), ('SUPPORT_BOOKED', 'Support Booked'), ('SUPPORT_CANCELLED', 'Support Cancelled'), ('SUPPORT_REMINDER', 'Support Reminder'), ('REWARD_EARNED', 'Reward Earned'), ('SHOP_ORDER_READY', 'Shop Order Ready'), ('STRIKE_LOST', 'Strike Lost'), ('SYSTEM', 'System')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=160)),
                ('body', models.CharField(blank=True, default='', max_length=400)),
                ('link_url', models.CharField(blank=True, default='', max_length=300)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_2d3764_idx'), models.Index(fields=['recipient', 'category', 'read_at'], name='notificatio_recipie_628850_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True)),
                ('p256dh', models.CharField(max_length=200)),
                ('auth', models.CharField(max_length=100)),
                ('user_agent', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('failed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_push_subscriptions',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['user', 'failed_at'], name='notificatio_user_id_549912_idx')],
            },
        ),
    ]
