# Generated by Django 6.0.3 on 2026-09-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('GRADES', 'Grades'), ('HOMEWORK', 'Homework'), ('CLASSROOM', 'Classroom'), ('EXAMS', 'Exams'), ('SUPPORT', 'Support'), ('REWARDS', 'Rewards & Shop'), ('EVENTS', 'Events'), ('SYSTEM', 'System')], db_index=True, default='SYSTEM', max_length=16),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('HOMEWORK_GRADED', 'Homework Graded'), ('MIDTERM_RESULT', 'Midterm Result'), ('CERTIFICATE_READY', 'Certificate Ready'), ('HOMEWORK_ASSIGNED', 'Homework Assigned'), ('HOMEWORK_DUE_SOON', 'Homework Due Soon'), ('MIDTERM_SCHEDULED', 'Midterm Scheduled'), ('CLASS_ANNOUNCEMENT', 'Class Announcement'), ('TELEGRAM_GROUP', 'Telegram Group'), ('COMMENT_REPLY', 'Comment Reply'), ('SUPPORT_BOOKED', 'Support Booked'), ('SUPPORT_CANCELLED', 'Support Cancelled'), ('SUPPORT_REMINDER', 'Support Reminder'), ('EVENT_PUBLISHED', 'Event Published'), ('EVENT_REMINDER', 'Event Reminder'), ('EVENT_CHANGED', 'Event Changed'), ('EVENT_CANCELLED', 'Event Cancelled'), ('REWARD_EARNED', 'Reward Earned'), ('SHOP_ORDER_READY', 'Shop Order Ready'), ('STRIKE_LOST', 'Strike Lost'), ('SYSTEM', 'System')], db_index=True, max_length=32),
        ),
    ]
