# Generated by Django 6.0.3 on 2026-09-25 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_events_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApnsDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, unique=True)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox (development builds)'), ('production', 'Production')], default='production', max_length=16)),
                ('bundle_id', models.CharField(blank=True, default='', max_length=128)),
                ('app_version', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('failed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apns_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_apns_devices',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['user', 'failed_at'], name='notif_apns_user_failed')],
            },
        ),
    ]
