# Generated by Django 6.0.3 on 2026-07-08 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0050_alter_module_practice_test'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Midterm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('subject', models.CharField(choices=[('READING_WRITING', 'Reading & Writing'), ('MATH', 'Math')], db_index=True, default='READING_WRITING', max_length=20)),
                ('scoring_scale', models.CharField(choices=[('SCALE_100', '100-point (percentage)'), ('SCALE_800', '800-point (SAT scaled)')], default='SCALE_100', max_length=16)),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Single-module strict timer.')),
                ('question_limit', models.PositiveSmallIntegerField(default=30, help_text='Authoring cap on question count.')),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('legacy_mock_exam_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('question_module', models.OneToOneField(blank=True, help_text="Owned exams.Module holding this midterm's questions.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='midterm', to='exams.module')),
            ],
            options={
                'db_table': 'midterms_midterm',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MidtermAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('flagged', models.JSONField(blank=True, default=list)),
                ('current_state', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('ACTIVE', 'Active'), ('SCORING', 'Scoring'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], db_index=True, default='NOT_STARTED', max_length=24)),
                ('version_number', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('scoring_started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('legacy_test_attempt_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('midterm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='midterms.midterm')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midterm_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'midterms_attempt',
            },
        ),
        migrations.CreateModel(
            name='MidtermAttemptEngineAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=64)),
                ('from_state', models.CharField(blank=True, max_length=24)),
                ('to_state', models.CharField(blank=True, max_length=24)),
                ('version_number', models.PositiveIntegerField(default=0)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_audit', to='midterms.midtermattempt')),
            ],
            options={
                'db_table': 'midterms_attempt_engine_audit',
            },
        ),
        migrations.CreateModel(
            name='MidtermAttemptIdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(db_index=True, max_length=64)),
                ('key', models.CharField(db_index=True, max_length=128)),
                ('response_status', models.PositiveSmallIntegerField(default=200)),
                ('response_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to='midterms.midtermattempt')),
            ],
            options={
                'db_table': 'midterms_attempt_idempotency_keys',
            },
        ),
        migrations.AddIndex(
            model_name='midtermattempt',
            index=models.Index(fields=['midterm', 'student'], name='midterms_at_midterm_7110ea_idx'),
        ),
        migrations.AddIndex(
            model_name='midtermattempt',
            index=models.Index(fields=['current_state'], name='midterms_at_current_6676fb_idx'),
        ),
        migrations.AddIndex(
            model_name='midtermattempt',
            index=models.Index(fields=['scoring_started_at'], name='midterms_at_scoring_319021_idx'),
        ),
        migrations.AddConstraint(
            model_name='midtermattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('is_completed', False), models.Q(('current_state', 'ABANDONED'), _negated=True)), fields=('student', 'midterm'), name='uniq_active_midterm_attempt_per_student'),
        ),
        migrations.AddConstraint(
            model_name='midtermattemptidempotencykey',
            constraint=models.UniqueConstraint(fields=('attempt', 'endpoint', 'key'), name='uniq_midterm_attempt_endpoint_key'),
        ),
    ]
