# Generated by Django 6.0.3 on 2026-07-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midterms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='midtermattempt',
            name='code_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
