# Generated by Django 6.0.3 on 2026-07-11 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0033_midtermschedule_access_code_and_more'),
        ('exams', '0051_mockexam_midterm_level_mockexam_midterm_period_and_more'),
        ('midterms', '0002_midtermattempt_code_verified_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MidtermVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveSmallIntegerField()),
                ('label', models.CharField(blank=True, default='', max_length=64)),
                ('legacy_practice_test_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('midterm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='midterms.midterm')),
                ('question_module', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='midterm_version', to='exams.module')),
            ],
            options={
                'db_table': 'midterms_version',
                'ordering': ['version_number'],
            },
        ),
        migrations.AddField(
            model_name='midtermattempt',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='midterms.midtermversion'),
        ),
        migrations.CreateModel(
            name='MidtermVersionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='classes.classroom')),
                ('midterm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_assignments', to='midterms.midterm')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='midterms.midtermversion')),
            ],
            options={
                'db_table': 'midterms_version_assignment',
            },
        ),
        migrations.AddConstraint(
            model_name='midtermversion',
            constraint=models.UniqueConstraint(fields=('midterm', 'version_number'), name='uniq_midterm_version_number'),
        ),
        migrations.AddConstraint(
            model_name='midtermversionassignment',
            constraint=models.UniqueConstraint(fields=('midterm', 'classroom', 'student'), name='uniq_midterm_version_assignment'),
        ),
    ]
