# Generated by Django 6.0.3 on 2026-07-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midterms', '0003_midtermversion_midtermattempt_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='midterm',
            name='level',
            field=models.CharField(blank=True, choices=[('foundation', 'Foundation'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], db_index=True, default='', help_text='Blank = untagged (no calculator). Foundation applies to Math only.', max_length=16),
        ),
    ]
