# Generated by Django 6.0.3 on 2026-07-20 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midterms', '0004_midterm_level'),
        ('questionbank', '0004_bankquestionattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='midterm',
            name='midterm_type',
            field=models.CharField(choices=[('PRE_MIDTERM', 'Pre-midterm'), ('MIDTERM', 'Midterm'), ('RETAKE', 'Retake midterm')], db_index=True, default='MIDTERM', help_text='Pre-midterm / midterm / retake. Pre-midterms are never pass/fail graded.', max_length=16),
        ),
        migrations.AddField(
            model_name='midterm',
            name='pass_mark',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Score a student must reach to PASS, on this midterm's own scale (0-100 or 200-800). Blank = the 50%-of-questions default for the scale.", null=True),
        ),
        migrations.AddField(
            model_name='midterm',
            name='retake_of',
            field=models.ForeignKey(blank=True, help_text='For a RETAKE: the midterm whose failers may sit this.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retakes', to='midterms.midterm'),
        ),
        migrations.AddField(
            model_name='midtermattempt',
            name='offscreen_violations',
            field=models.PositiveSmallIntegerField(default=0, help_text='Times the student left the exam window during this attempt.'),
        ),
        migrations.AddField(
            model_name='midtermattempt',
            name='terminated_reason',
            field=models.CharField(blank=True, choices=[('OFFSCREEN', 'Left the exam window')], db_index=True, default='', max_length=24),
        ),
        migrations.CreateModel(
            name='MidtermOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('pass_mark', models.PositiveSmallIntegerField()),
                ('scoring_scale', models.CharField(blank=True, default='', max_length=16)),
                ('passed', models.BooleanField(db_index=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcome_rows', to='midterms.midtermattempt')),
                ('midterm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='midterms.midterm')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midterm_outcomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'midterms_outcome',
                'ordering': ['-decided_at'],
                'indexes': [models.Index(fields=['midterm', 'passed'], name='midterms_ou_midterm_eb11dc_idx')],
                'constraints': [models.UniqueConstraint(fields=('midterm', 'student'), name='uniq_midterm_outcome_per_student')],
            },
        ),
        migrations.CreateModel(
            name='MidtermQuestionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.BigIntegerField(db_index=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_correct', models.BooleanField(db_index=True, default=False)),
                ('answered', models.BooleanField(default=False, help_text='False = omitted (counts as wrong).')),
                ('skill_name', models.CharField(blank=True, default='', max_length=255)),
                ('domain_name', models.CharField(blank=True, default='', max_length=255)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_results', to='midterms.midtermattempt')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='questionbank.bankskill')),
            ],
            options={
                'db_table': 'midterms_question_result',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['attempt', 'is_correct'], name='midterms_qu_attempt_ba6e29_idx')],
                'constraints': [models.UniqueConstraint(fields=('attempt', 'question_id'), name='uniq_midterm_qresult_per_attempt')],
            },
        ),
    ]
