# Generated by Django 6.0.3 on 2026-07-28 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0054_mockexam_midterm_two_module_runtime'),
        ('midterms', '0005_midterm_midterm_type_midterm_pass_mark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='midterm',
            name='duration_minutes_2',
            field=models.PositiveIntegerField(blank=True, help_text='Module-2 strict timer (null = single-module midterm).', null=True),
        ),
        migrations.AddField(
            model_name='midterm',
            name='question_module_2',
            field=models.OneToOneField(blank=True, help_text='Owned exams.Module for the SECOND timed module (null = single-module).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='midterm_module2', to='exams.module'),
        ),
        migrations.AddField(
            model_name='midtermattempt',
            name='module_2_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='midtermversion',
            name='question_module_2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='midterm_version_module2', to='exams.module'),
        ),
        migrations.AlterField(
            model_name='midtermattempt',
            name='current_state',
            field=models.CharField(choices=[('NOT_STARTED', 'Not started'), ('ACTIVE', 'Active'), ('MODULE_2_ACTIVE', 'Module 2 active'), ('SCORING', 'Scoring'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], db_index=True, default='NOT_STARTED', max_length=24),
        ),
    ]
