# Generated by Django 6.0.3 on 2026-07-29 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0036_assignment_notified_at'),
        ('midterms', '0006_midterm_duration_minutes_2_midterm_question_module_2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='midtermversionassignment',
            name='seat_col',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='midtermversionassignment',
            name='seat_row',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='midtermversionassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('seat_col__isnull', False), ('seat_row__isnull', False)), fields=('midterm', 'classroom', 'seat_row', 'seat_col'), name='uniq_midterm_classroom_seat'),
        ),
    ]
