# Generated by Django 6.0.3 on 2026-08-04 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midterms', '0007_midtermversionassignment_seat_col_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MidtermResit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, default='', help_text="Why this student may sit it again — e.g. 'repeated the first month'.", max_length=255)),
                ('consumed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='midterms.midtermattempt')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('midterm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resits', to='midterms.midterm')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midterm_resits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'midterms_resit',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['midterm', 'student', 'consumed_at'], name='midterms_re_midterm_bf4983_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('consumed_at__isnull', True)), fields=('midterm', 'student'), name='uniq_open_midterm_resit')],
            },
        ),
    ]
