# Generated by Django 6.0.3 on 2026-09-18 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0054_mockexam_midterm_two_module_runtime'),
        ('midterms', '0008_midtermresit'),
    ]

    operations = [
        migrations.AddField(
            model_name='midtermattempt',
            name='paper_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='exams.module'),
        ),
        migrations.AddField(
            model_name='midtermattempt',
            name='paper_module_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='exams.module'),
        ),
        migrations.AddField(
            model_name='midtermattempt',
            name='paper_pass_mark',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='midtermattempt',
            name='paper_scale',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
