# Generated by Django 6.0.3 on 2026-08-08 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('exam', 'Exam / pastpaper'), ('assessment', 'Assessment'), ('vocab', 'Vocabulary')], db_index=True, max_length=16)),
                ('ref', models.CharField(db_index=True, max_length=64)),
                ('target_id', models.BigIntegerField()),
                ('container', models.CharField(max_length=32)),
                ('data', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_annotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'study_annotations',
                'ordering': ['target_id', 'container'],
                'indexes': [models.Index(fields=['student', 'scope', 'ref'], name='study_annot_student_897783_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'scope', 'ref', 'target_id', 'container'), name='uniq_annotation_per_region')],
            },
        ),
    ]
