# Generated by Django 6.0.3 on 2026-06-30 05:46

from django.db import migrations, models

# Temp band must exceed any plausible dense index; used only inside this migration.
_ORDER_TEMP_BASE = 10_000_000


def _normalize_all_orders(apps, schema_editor):
    """
    Make every set's question `order` a unique, contiguous 0..n-1 sequence BEFORE
    the UNIQUE(assessment_set, order) constraint is added, so legacy duplicate /
    gapped orders can't make the constraint creation fail.

    Preserves the current visible order — questions are renumbered in their
    existing (order, id) sequence, only removing duplicates and gaps. Two-phase
    temp band keeps it valid regardless of statement ordering.
    """
    AssessmentQuestion = apps.get_model("assessments", "AssessmentQuestion")
    set_ids = list(
        AssessmentQuestion.objects.order_by()
        .values_list("assessment_set_id", flat=True)
        .distinct()
    )
    for sid in set_ids:
        rows = list(
            AssessmentQuestion.objects.filter(assessment_set_id=sid).order_by("order", "id")
        )
        if all(q.order == i for i, q in enumerate(rows)):
            continue  # already dense
        for i, q in enumerate(rows):
            q.order = _ORDER_TEMP_BASE + i
        AssessmentQuestion.objects.bulk_update(rows, ["order"])
        for i, q in enumerate(rows):
            q.order = i
        AssessmentQuestion.objects.bulk_update(rows, ["order"])


def _noop_reverse(apps, schema_editor):
    # Renumbering is not reversible (the pre-normalization orders are lost), but
    # the data remains valid, so reverse is a safe no-op.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0021_assessmentquestion_bank_question_and_more'),
        ('questionbank', '0004_bankquestionattempt'),
    ]

    # Data-normalization only. The UNIQUE(assessment_set, order) constraint is
    # added in the FOLLOWING migration (0023), NOT here: on PostgreSQL you cannot
    # `ALTER TABLE ... ADD CONSTRAINT` in the same transaction that just ran the
    # RunPython bulk updates ("cannot ALTER TABLE ... because it has pending
    # trigger events"). Django wraps each migration in its own transaction, so
    # splitting the schema change into 0023 lets the normalization commit first.
    operations = [
        migrations.RemoveIndex(
            model_name='assessmentquestion',
            name='assessment__assessm_a256a3_idx',
        ),
        migrations.RunPython(_normalize_all_orders, _noop_reverse),
    ]
