# Generated by Django 6.0.3 on 2026-07-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0023_uniq_assessment_question_order_per_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentset',
            name='source',
            field=models.CharField(blank=True, choices=[('SQB', 'SQB'), ('SATOPLAM', 'SAToplam'), ('MATHBOOK', 'Mathbook'), ('PREP_PROS', 'Prep Pros'), ('HARD_QUESTIONS', 'Hard questions'), ('EXTERNAL', 'External source')], db_index=True, default='', max_length=32),
        ),
    ]
