# Generated by Django 6.0.3 on 2026-07-04 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0024_assessmentset_source'),
        ('classes', '0026_assignment_practice_test_pack_ids'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='homeworkassignment',
            name='uniq_assessment_hw_class_assignment',
        ),
        migrations.AlterField(
            model_name='homeworkassignment',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_homeworks', to='classes.assignment'),
        ),
    ]
