# Generated by Django 6.0.3 on 2026-07-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0025_remove_homeworkassignment_uniq_assessment_hw_class_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentset',
            name='level',
            field=models.CharField(blank=True, choices=[('foundation', 'Foundation'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], db_index=True, default='', max_length=16),
        ),
    ]
