# Generated by Django 6.0.3 on 2026-07-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0026_assessmentset_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentattempt',
            name='current_question_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='paused_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='paused_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assessmentattemptauditevent',
            name='event_type',
            field=models.CharField(choices=[('started', 'Started'), ('answer_saved', 'Answer saved'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('abandoned', 'Abandoned'), ('timeout_abandoned', 'Timeout abandoned'), ('paused', 'Paused'), ('resumed', 'Resumed')], db_index=True, max_length=40),
        ),
    ]
