# Generated by Django 6.0.3 on 2026-07-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0027_assessmentattempt_current_question_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governanceevent',
            name='event_type',
            field=models.CharField(choices=[('publish', 'Published'), ('publish_idempotent', 'Publish (idempotent — identical content)'), ('publish_validation_failed', 'Publish validation failed'), ('supersede', 'Superseded by new version'), ('set_delete', 'Assessment set deleted'), ('assignment_pin', 'Assignment version pinned'), ('attempt_snapshot_pin', 'Attempt snapshot pinned'), ('scoring_start', 'Scoring started'), ('scoring_complete', 'Scoring completed'), ('scoring_retry', 'Scoring retried'), ('scoring_failure', 'Scoring failed'), ('scoring_override', 'Scoring overridden'), ('integrity_failure', 'Integrity failure detected'), ('integrity_repair', 'Integrity repair performed'), ('fallback_path_used', 'Live-read fallback path used (pre-snapshot attempt)')], db_index=True, max_length=64),
        ),
    ]
