# Generated by Django 6.0.3 on 2026-07-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0029_assessmentset_review_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assessmentsetversion',
            name='uniq_set_version_number',
        ),
        migrations.RemoveConstraint(
            model_name='assessmentsetversion',
            name='uniq_set_version_checksum',
        ),
        migrations.RemoveField(
            model_name='homeworkassignment',
            name='set_version',
        ),
        migrations.RemoveField(
            model_name='assessmentattempt',
            name='set_version',
        ),
        migrations.RemoveField(
            model_name='assessmentquestion',
            name='bank_version',
        ),
        migrations.DeleteModel(
            name='AssessmentSetVersion',
        ),
    ]
