# Generated by Django 6.0.3 on 2026-08-14 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rewards', '0005_studentstrike_striketransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_items/')),
                ('currency', models.CharField(choices=[('COIN', 'Coins'), ('STRIKE', 'Strikes')], db_index=True, default='COIN', max_length=8)),
                ('price', models.PositiveIntegerField(help_text="Cost in the item's own currency.")),
                ('stock', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Unticked hides it from students without deleting anything they have ordered.')),
                ('sort_order', models.IntegerField(default=0, help_text='Lower shows first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shop_items',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('COIN', 'Coins'), ('STRIKE', 'Strikes')], max_length=8)),
                ('price', models.PositiveIntegerField()),
                ('item_name', models.CharField(help_text='Frozen too — a renamed item must not rewrite old orders.', max_length=140)),
                ('status', models.CharField(choices=[('PENDING', 'Waiting to be handed over'), ('FULFILLED', 'Handed over'), ('CANCELLED', 'Cancelled and refunded')], db_index=True, default='PENDING', max_length=12)),
                ('note', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('settled_at', models.DateTimeField(blank=True, help_text='When it was fulfilled or cancelled.', null=True)),
                ('coin_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_orders', to='rewards.cointransaction')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shop.shopitem')),
                ('settled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shop_orders',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='shopitem',
            index=models.Index(fields=['currency', 'is_active', 'sort_order'], name='shop_items_currenc_0db8c5_idx'),
        ),
        migrations.AddIndex(
            model_name='shoporder',
            index=models.Index(fields=['student', '-created_at'], name='shop_orders_student_2cea7f_idx'),
        ),
        migrations.AddIndex(
            model_name='shoporder',
            index=models.Index(fields=['status', '-created_at'], name='shop_orders_status_266a55_idx'),
        ),
    ]
