# Generated by Django 6.0.3 on 2026-09-21 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0030_remove_assessmentsetversion_uniq_set_version_number_and_more'),
        ('classes', '0052_telegramstarttoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveQuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('join_code', models.CharField(db_index=True, max_length=6)),
                ('status', models.CharField(choices=[('LOBBY', 'Lobby'), ('STARTING', 'Starting'), ('QUESTION_ACTIVE', 'Question active'), ('QUESTION_RESULTS', 'Question results'), ('PAUSED', 'Paused'), ('FINISHED', 'Finished'), ('TERMINATED', 'Terminated')], db_index=True, default='LOBBY', max_length=20)),
                ('current_index', models.IntegerField(default=-1, help_text="0-based index into this session's questions; -1 before the first.")),
                ('question_started_at', models.DateTimeField(blank=True, null=True)),
                ('question_ends_at', models.DateTimeField(blank=True, help_text='Server-side deadline for the open question.', null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('paused_from', models.CharField(blank=True, default='', help_text='Status to restore on resume.', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('assessment_set', models.ForeignKey(help_text='Where the questions came from. PROTECT: a played session must stay readable.', on_delete=django.db.models.deletion.PROTECT, related_name='live_quiz_sessions', to='assessments.assessmentset')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_quiz_sessions', to='classes.classroom')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_live_quizzes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'livequiz_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(help_text='0-based position in this session.')),
                ('prompt', models.TextField()),
                ('question_prompt', models.TextField(blank=True, default='')),
                ('question_type', models.CharField(max_length=32)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.JSONField(blank=True, default=None, null=True)),
                ('grading_config', models.JSONField(blank=True, default=dict)),
                ('points', models.PositiveIntegerField(default=1)),
                ('explanation', models.TextField(blank=True, default='')),
                ('image_paths', models.JSONField(blank=True, default=dict)),
                ('time_limit_seconds', models.PositiveIntegerField(default=20)),
                ('source_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_quiz_questions', to='assessments.assessmentquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='livequiz.livequizsession')),
            ],
            options={
                'db_table': 'livequiz_question',
                'ordering': ['session_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LiveQuizParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('JOINED', 'Joined'), ('LEFT', 'Left'), ('KICKED', 'Removed by host')], db_index=True, default='JOINED', max_length=16)),
                ('connections', models.PositiveIntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('answered_count', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(blank=True, help_text='Final placing, set at finish.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_quiz_participations', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='livequiz.livequizsession')),
            ],
            options={
                'db_table': 'livequiz_participant',
                'ordering': ['-score', 'joined_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveQuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.JSONField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('response_time_ms', models.PositiveIntegerField(default=0, help_text='From the question opening to the answer landing, server-measured.')),
                ('points_awarded', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='livequiz.livequizparticipant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='livequiz.livequizquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='livequiz.livequizsession')),
            ],
            options={
                'db_table': 'livequiz_answer',
                'ordering': ['question_id', 'submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='livequizsession',
            index=models.Index(fields=['classroom', 'status'], name='livequiz_se_classro_81171b_idx'),
        ),
        migrations.AddIndex(
            model_name='livequizsession',
            index=models.Index(fields=['status', '-created_at'], name='livequiz_se_status_d113d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='livequizsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['LOBBY', 'STARTING', 'QUESTION_ACTIVE', 'QUESTION_RESULTS', 'PAUSED'])), fields=('join_code',), name='uniq_livequiz_active_join_code'),
        ),
        migrations.AddConstraint(
            model_name='livequizquestion',
            constraint=models.UniqueConstraint(fields=('session', 'order'), name='uniq_livequiz_question_order'),
        ),
        migrations.AddIndex(
            model_name='livequizparticipant',
            index=models.Index(fields=['session', '-score'], name='livequiz_pa_session_7bc296_idx'),
        ),
        migrations.AddConstraint(
            model_name='livequizparticipant',
            constraint=models.UniqueConstraint(fields=('session', 'user'), name='uniq_livequiz_participant'),
        ),
        migrations.AddIndex(
            model_name='livequizanswer',
            index=models.Index(fields=['session', 'question'], name='livequiz_an_session_0a05ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='livequizanswer',
            constraint=models.UniqueConstraint(fields=('participant', 'question'), name='uniq_livequiz_answer_per_question'),
        ),
    ]
