# Generated by Django 6.0.3 on 2026-10-08 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('midterms', '0009_attempt_paper_pins'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MidtermLockdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False)),
                ('nonce_hash', models.CharField(blank=True, max_length=64)),
                ('nonce_expires_at', models.DateTimeField(blank=True, null=True)),
                ('session_hash', models.CharField(blank=True, max_length=64)),
                ('session_opened_at', models.DateTimeField(blank=True, null=True)),
                ('sessions_opened', models.PositiveIntegerField(default=0)),
                ('app_version', models.CharField(blank=True, max_length=32)),
                ('key_id', models.CharField(blank=True, max_length=32)),
                ('precheck', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lockdown', to='midterms.midtermattempt')),
            ],
            options={
                'db_table': 'desktop_midterm_lockdown',
            },
        ),
        migrations.CreateModel(
            name='DesktopAuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64, unique=True)),
                ('challenge', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'desktop_auth_code',
                'indexes': [models.Index(fields=['expires_at'], name='desktop_auth_code_exp')],
            },
        ),
        migrations.CreateModel(
            name='DesktopExemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desktop_exemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'desktop_exemption',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('student',), name='uniq_desktop_exemption_live')],
            },
        ),
    ]
