# Generated by Django 6.0.3 on 2026-07-10 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramReportSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=64, unique=True)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('first_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'question_report_telegram_subscribers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('exam', 'Exam (pastpaper / practice / mock / midterm)'), ('assessment', 'Assessment')], db_index=True, max_length=16)),
                ('question_id', models.BigIntegerField(db_index=True)),
                ('attempt_id', models.BigIntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('wrong_answer', 'Wrong / no correct answer'), ('answer_key', 'Answer key looks wrong'), ('typo_unclear', 'Typo / unclear wording'), ('image_figure', 'Image / figure problem'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('message', models.TextField(blank=True, default='', max_length=2000)),
                ('resource_type', models.CharField(choices=[('pastpaper', 'Pastpaper'), ('practice_test', 'Practice test'), ('assessment', 'Assessment'), ('mock', 'Mock exam'), ('midterm', 'Midterm'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20)),
                ('resource_id', models.BigIntegerField(blank=True, null=True)),
                ('resource_title', models.CharField(blank=True, default='', max_length=255)),
                ('question_order', models.PositiveIntegerField(blank=True, help_text='1-based number.', null=True)),
                ('question_excerpt', models.CharField(blank=True, default='', max_length=280)),
                ('qb_id', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEWING', 'Reviewing'), ('FIXED', 'Fixed'), ('REJECTED', 'Rejected'), ('DUPLICATE', 'Duplicate')], db_index=True, default='NEW', max_length=12)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_error_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'question_error_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['system', 'question_id'], name='question_er_system_8cc664_idx'), models.Index(fields=['status', '-created_at'], name='question_er_status_bf2815_idx')],
            },
        ),
    ]
