# Generated by Django 6.0.3 on 2026-07-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionerrorreport',
            name='resolved_by_label',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='questionerrorreport',
            name='telegram_messages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
