# Generated by Django 6.0.3 on 2026-07-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_reports', '0002_questionerrorreport_resolved_by_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionerrorreport',
            name='module_label',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='questionerrorreport',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
