# Generated by Django 6.0.3 on 2026-08-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_reports', '0003_questionerrorreport_module_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionerrorreport',
            name='level',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
