# Generated by Django 6.0.3 on 2026-08-06 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0040_attendance_session_unique_per_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('ATTENDANCE_PRESENT', 'Attended a lesson'), ('ATTENDANCE_LATE', 'Attended a lesson (late)'), ('SUPPORT_SESSION', 'Support-teacher session held'), ('SURVEY', 'Survey completed'), ('MIDTERM_PASS', 'Midterm passed'), ('MIDTERM_RETAKE_PASS', 'Midterm retake passed'), ('HOMEWORK_FULL', 'Homework 100%'), ('HOMEWORK_HIGH', 'Homework 80–99%'), ('HOMEWORK_MID', 'Homework 60–79%'), ('MANUAL', 'Manual adjustment')], db_index=True, max_length=40)),
                ('points', models.IntegerField(default=0)),
                ('source_type', models.CharField(blank=True, max_length=40)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('awarded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_awards', to='classes.classroom')),
                ('created_by', models.ForeignKey(blank=True, help_text='Null for a system award.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_awards_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_awards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reward_point_awards',
                'ordering': ['-awarded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PointAwardAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_points', models.IntegerField(blank=True, help_text='Null on first grant.', null=True)),
                ('new_points', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Null for a system change.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='rewards.pointaward')),
            ],
            options={
                'db_table': 'reward_point_award_audit',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RewardRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('ATTENDANCE_PRESENT', 'Attended a lesson'), ('ATTENDANCE_LATE', 'Attended a lesson (late)'), ('SUPPORT_SESSION', 'Support-teacher session held'), ('SURVEY', 'Survey completed'), ('MIDTERM_PASS', 'Midterm passed'), ('MIDTERM_RETAKE_PASS', 'Midterm retake passed'), ('HOMEWORK_FULL', 'Homework 100%'), ('HOMEWORK_HIGH', 'Homework 80–99%'), ('HOMEWORK_MID', 'Homework 60–79%'), ('MANUAL', 'Manual adjustment')], max_length=40, unique=True)),
                ('points', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reward_rules',
                'ordering': ['event'],
            },
        ),
        migrations.CreateModel(
            name='RewardSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reward_seasons',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='pointaward',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awards', to='rewards.rewardseason'),
        ),
        migrations.AddConstraint(
            model_name='rewardseason',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='uniq_single_current_reward_season'),
        ),
        migrations.AddIndex(
            model_name='pointaward',
            index=models.Index(fields=['student', 'season'], name='reward_poin_student_acef6d_idx'),
        ),
        migrations.AddIndex(
            model_name='pointaward',
            index=models.Index(fields=['season', 'classroom'], name='reward_poin_season__fb0750_idx'),
        ),
        migrations.AddIndex(
            model_name='pointaward',
            index=models.Index(fields=['student', '-awarded_at'], name='reward_poin_student_03147e_idx'),
        ),
    ]
