# Generated by Django 6.0.3 on 2026-08-07 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_seed_reward_rules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardseason',
            name='points_per_coin',
            field=models.PositiveSmallIntegerField(default=10, help_text='Points needed to mint one coin.'),
        ),
        migrations.CreateModel(
            name='StudentWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins_balance', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coin_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reward_wallets',
            },
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('EARN', 'Earned from points'), ('SPEND', 'Spent'), ('ADMIN_GRANT', 'Granted by an admin'), ('ADMIN_REVOKE', 'Taken back by an admin')], db_index=True, max_length=14)),
                ('amount', models.IntegerField(help_text='Signed: positive adds coins, negative removes them.')),
                ('balance_after', models.IntegerField()),
                ('reference', models.CharField(blank=True, help_text='What it was spent on, or why it was adjusted.', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Null for an automatic mint.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coin_mints', to='rewards.rewardseason')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='rewards.studentwallet')),
            ],
            options={
                'db_table': 'reward_coin_transactions',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['wallet', '-created_at'], name='reward_coin_wallet__ed4114_idx'), models.Index(fields=['wallet', 'kind', 'season'], name='reward_coin_wallet__4aa178_idx')],
            },
        ),
    ]
