# Generated by Django 6.0.3 on 2026-08-14 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0004_pointaward_xp_pointawardaudit_new_xp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStrike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('best_streak', models.PositiveIntegerField(default=0)),
                ('spent_in_streak', models.PositiveIntegerField(default=0, help_text='Spent since the streak last broke. balance = current_streak - this.')),
                ('last_counted_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strike_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reward_student_strikes',
            },
        ),
        migrations.CreateModel(
            name='StrikeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('SPEND', 'Spent'), ('RESET', 'Reset by a missed lesson'), ('ADMIN_GRANT', 'Granted by an admin')], db_index=True, max_length=14)),
                ('amount', models.IntegerField(help_text='Signed: negative removes strikes.')),
                ('balance_after', models.IntegerField()),
                ('reference', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Null for an automatic reset.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strike_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reward_strike_transactions',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['student', '-created_at'], name='reward_stri_student_613ee9_idx')],
            },
        ),
    ]
