# Generated by Django 6.0.3 on 2026-08-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0006_rewardrule_grants_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cointransaction',
            name='points_spent',
            field=models.PositiveIntegerField(default=0, help_text='Points consumed by this mint. Zero for spends and adjustments.'),
        ),
        migrations.AlterField(
            model_name='pointaward',
            name='event',
            field=models.CharField(choices=[('ATTENDANCE_PRESENT', 'Attended a lesson'), ('ATTENDANCE_LATE', 'Attended a lesson (late)'), ('SUPPORT_SESSION', 'Support-teacher session held'), ('SURVEY', 'Survey completed'), ('MIDTERM_PASS', 'Midterm passed'), ('MIDTERM_RETAKE_PASS', 'Midterm retake passed'), ('HOMEWORK', 'Homework completed'), ('CLASSWORK_MANUAL', 'Classwork awarded by a teacher'), ('MANUAL', 'Manual adjustment'), ('COIN_CONVERSION', 'Turned into coins'), ('HOMEWORK_FULL', 'Homework 100%'), ('HOMEWORK_HIGH', 'Homework 80–99%'), ('HOMEWORK_MID', 'Homework 60–79%')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='rewardrule',
            name='event',
            field=models.CharField(choices=[('ATTENDANCE_PRESENT', 'Attended a lesson'), ('ATTENDANCE_LATE', 'Attended a lesson (late)'), ('SUPPORT_SESSION', 'Support-teacher session held'), ('SURVEY', 'Survey completed'), ('MIDTERM_PASS', 'Midterm passed'), ('MIDTERM_RETAKE_PASS', 'Midterm retake passed'), ('HOMEWORK', 'Homework completed'), ('CLASSWORK_MANUAL', 'Classwork awarded by a teacher'), ('MANUAL', 'Manual adjustment'), ('COIN_CONVERSION', 'Turned into coins'), ('HOMEWORK_FULL', 'Homework 100%'), ('HOMEWORK_HIGH', 'Homework 80–99%'), ('HOMEWORK_MID', 'Homework 60–79%')], max_length=40, unique=True),
        ),
    ]
