# Generated by Django 6.0.3 on 2026-06-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0048_drop_pastpaperpack'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockexam',
            name='midterm_module_question_limit',
            field=models.PositiveSmallIntegerField(default=30, help_text='Only used when kind=MIDTERM. Max questions allowed per module.'),
        ),
    ]
