# Generated by Django 6.0.3 on 2026-07-08 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0049_mockexam_midterm_module_question_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='practice_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='exams.practicetest'),
        ),
    ]
