# Generated by Django 6.0.3 on 2026-07-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0050_alter_module_practice_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockexam',
            name='midterm_level',
            field=models.CharField(blank=True, choices=[('foundation', 'Foundation'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], db_index=True, default='', help_text='Only used when kind=MIDTERM. Foundation applies to Math only.', max_length=16),
        ),
        migrations.AddField(
            model_name='mockexam',
            name='midterm_period',
            field=models.CharField(blank=True, choices=[('FIRST_MONTH', 'First month'), ('SECOND_MONTH', 'Second month'), ('THIRD_MONTH', 'Third month')], db_index=True, default='', help_text='Only used when kind=MIDTERM. Monthly round the midterm belongs to.', max_length=16),
        ),
        migrations.AddField(
            model_name='mockexam',
            name='midterm_type',
            field=models.CharField(choices=[('PRE_MIDTERM', 'Pre-midterm'), ('MIDTERM', 'Midterm'), ('RETAKE', 'Retake midterm')], db_index=True, default='MIDTERM', help_text='Only used when kind=MIDTERM. Pre-midterm / midterm / retake.', max_length=16),
        ),
    ]
