# Generated by Django 6.0.3 on 2026-07-20 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0051_mockexam_midterm_level_mockexam_midterm_period_and_more'),
        ('questionbank', '0004_bankquestionattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockexam',
            name='midterm_pass_mark',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Only used when kind=MIDTERM. Score needed to PASS, on this midterm's own scale (0-100 or 200-800). Blank = the 50%-of-questions default. Ignored for pre-midterms, which are never pass/fail graded.", null=True),
        ),
        migrations.AddField(
            model_name='mockexam',
            name='midterm_retake_of',
            field=models.ForeignKey(blank=True, help_text='Only used when midterm_type=RETAKE. The midterm whose FAILING students may sit this retake; passing students are never granted access.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='midterm_retakes', to='exams.mockexam'),
        ),
        migrations.AddField(
            model_name='question',
            name='skill',
            field=models.ForeignKey(blank=True, help_text='SAT skill this question tests. Drives the midterm error report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_questions', to='questionbank.bankskill'),
        ),
    ]
