# Generated by Django 6.0.3 on 2026-07-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0052_mockexam_midterm_pass_mark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='bank_version',
        ),
    ]
