# Generated by Django 6.0.3 on 2026-07-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0053_remove_question_bank_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockexam',
            name='midterm_two_module_runtime',
            field=models.BooleanField(default=False, help_text='Only used when kind=MIDTERM. Run as two sequential timed modules (module 1 timer -> auto-submit -> module 2 timer -> score). Off = single-module (both authored modules flattened into one timed module).'),
        ),
    ]
