# Generated by Django 6.0.3 on 2026-09-25 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppReleasePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('ios', 'iOS')], max_length=16, unique=True)),
                ('latest_version', models.CharField(blank=True, help_text='The newest build in the App Store, e.g. 1.2.0. Older builds are asked, never forced, to update. Leave empty to ask nobody.', max_length=32)),
                ('minimum_version', models.CharField(blank=True, help_text='The oldest build still allowed to use the app, e.g. 1.1.0. Older builds see an update screen and nothing else. Leave empty to allow every build.', max_length=32)),
                ('update_url', models.URLField(blank=True, help_text='The App Store page the Update button opens.', max_length=300)),
                ('message', models.CharField(blank=True, help_text='Optional sentence shown with the update prompt — what the new build brings.', max_length=280)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'app release policy',
                'verbose_name_plural': 'app release policies',
                'db_table': 'mobile_app_release_policy',
            },
        ),
        migrations.CreateModel(
            name='ClientDiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('ios', 'iOS')], default='ios', max_length=16)),
                ('install_id', models.CharField(max_length=64)),
                ('report_id', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('crash', 'Crash'), ('hang', 'Hang'), ('cpu', 'CPU limit'), ('disk', 'Disk writes'), ('error', 'App error')], max_length=16)),
                ('signature', models.CharField(max_length=200)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('app_version', models.CharField(blank=True, max_length=32)),
                ('build', models.CharField(blank=True, max_length=32)),
                ('os_version', models.CharField(blank=True, max_length=64)),
                ('device_model', models.CharField(blank=True, max_length=64)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mobile_client_diagnostic',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['kind', 'received_at'], name='mobile_diag_kind_recv'), models.Index(fields=['signature', 'received_at'], name='mobile_diag_sig_recv'), models.Index(fields=['app_version', 'received_at'], name='mobile_diag_ver_recv')],
                'constraints': [models.UniqueConstraint(fields=('install_id', 'report_id'), name='uniq_mobile_diagnostic_report')],
            },
        ),
    ]
