# Generated by Django 6.0.3 on 2026-10-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreleasepolicy',
            name='platform',
            field=models.CharField(choices=[('ios', 'iOS'), ('windows', 'Windows')], max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='clientdiagnostic',
            name='platform',
            field=models.CharField(choices=[('ios', 'iOS'), ('windows', 'Windows')], default='ios', max_length=16),
        ),
    ]
