# Generated by Django 6.0.3 on 2026-08-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='allow_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='survey_images/'),
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='follow_up',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='follow_up_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='follow_up_placeholder',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='follow_up_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='follow_up_threshold',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='survey_images/'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='scale_high_label',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='scale_low_label',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='question_type',
            field=models.CharField(choices=[('SHORT_TEXT', 'Short answer'), ('LONG_TEXT', 'Paragraph'), ('SINGLE_CHOICE', 'Multiple choice'), ('MULTI_CHOICE', 'Checkboxes'), ('SCALE', 'Linear scale'), ('RATING', 'Recommendation slider'), ('DATE', 'Date')], max_length=16),
        ),
    ]
