# Generated by Django 6.0.3 on 2026-08-30 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_survey_allow_anonymous_survey_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='condition_operator',
            field=models.CharField(blank=True, choices=[('AT_LEAST', 'scored at least'), ('BELOW', 'scored below'), ('ANY_OF', 'picked any of'), ('NONE_OF', 'picked none of'), ('ANSWERED', 'answered at all')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='condition_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_questions', to='surveys.surveyquestion'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='condition_value',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
