# Generated by Django 6.0.3 on 2026-08-30 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0048_classroommembershipevent'),
        ('surveys', '0003_surveyquestion_condition_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='audience_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='classes.branch'),
        ),
        migrations.AddField(
            model_name='survey',
            name='audience_classrooms',
            field=models.ManyToManyField(blank=True, related_name='surveys', to='classes.classroom'),
        ),
        migrations.AddField(
            model_name='survey',
            name='audience_kind',
            field=models.CharField(choices=[('ALL', 'Everyone'), ('LEVEL', 'One level'), ('CLASSROOMS', 'Chosen classrooms'), ('BRANCH', 'One branch')], db_index=True, default='ALL', max_length=12),
        ),
        migrations.AddField(
            model_name='survey',
            name='audience_level',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='survey',
            name='points_award',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='max_selections',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to='classes.classroom'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='level',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
