# Generated by Django 6.0.3 on 2026-07-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0030_remove_assessmentsetversion_uniq_set_version_number_and_more'),
        ('exams', '0053_remove_question_bank_version'),
        ('questionbank', '0004_bankquestionattempt'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bankquestionversion',
            name='uniq_qb_question_version_number',
        ),
        migrations.RemoveField(
            model_name='bankquestion',
            name='current_version',
        ),
        migrations.DeleteModel(
            name='BankQuestionVersion',
        ),
    ]
