# Generated by Django 6.0.3 on 2026-09-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0005_remove_bankquestionversion_uniq_qb_question_version_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdomain',
            name='level',
            field=models.CharField(blank=True, choices=[('', 'SAT (every level)'), ('foundation', 'Foundation'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], db_index=True, default='', max_length=16),
        ),
    ]
