# Generated by Django 6.0.3 on 2026-08-23 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stories/')),
                ('title', models.CharField(help_text='The word or two under the circle. Keep it short — it wraps.', max_length=80)),
                ('caption', models.TextField(blank=True, default='', help_text='Shown inside the viewer, under the image. Optional.')),
                ('link_url', models.URLField(blank=True, default='', help_text='Optional: tapping the story opens this.', max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Unticked pulls it off the rail without deleting it or its image.')),
                ('sort_order', models.IntegerField(default=0, help_text='Lower shows first (leftmost).')),
                ('starts_at', models.DateTimeField(blank=True, help_text='Leave empty to put it up straight away.', null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Leave empty and it stays up until you untick it.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'stories',
                'db_table': 'stories',
                'ordering': ['sort_order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='stories_is_acti_efb9a3_idx')],
            },
        ),
    ]
