# Generated by Django 6.0.3 on 2026-07-27 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0035_assignment_external_urls'),
        ('vocabulary', '0004_userwordprogress_introduced_learning_phase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'vocab_homeworks',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VocabSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vocab_sections',
                'ordering': ['order', 'title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VocabSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vocab_sets',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VocabSetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vocab_set_items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VocabStudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('flashcard', 'Flashcard'), ('matching', 'Matching'), ('speed', 'Speed'), ('test', 'Test')], db_index=True, max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'vocab_study_sessions',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VocabWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=120)),
                ('definition', models.TextField()),
                ('part_of_speech', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('pronoun', 'Pronoun'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('interjection', 'Interjection'), ('other', 'Other')], default='other', max_length=24)),
                ('example', models.TextField(blank=True, default='')),
                ('synonyms', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vocab_bank_words',
                'ordering': ['word', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VocabWordProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('mastered', 'Mastered')], db_index=True, default='new', max_length=16)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('streak', models.PositiveIntegerField(default=0)),
                ('last_reviewed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vocab_progress',
            },
        ),
        migrations.RemoveIndex(
            model_name='reviewlog',
            name='vocab_revie_user_id_d6b15e_idx',
        ),
        migrations.RemoveIndex(
            model_name='reviewlog',
            name='vocab_revie_user_id_dd1ba8_idx',
        ),
        migrations.RemoveIndex(
            model_name='uservocabularyprogress',
            name='vocabulary__user_id_1ea9d6_idx',
        ),
        migrations.RemoveIndex(
            model_name='uservocabularyprogress',
            name='vocabulary__user_id_e9efae_idx',
        ),
        migrations.RemoveConstraint(
            model_name='uservocabularyprogress',
            name='uniq_vocab_user_word',
        ),
        migrations.RemoveIndex(
            model_name='uservocabularyreviewevent',
            name='vocabulary__user_id_ba88d4_idx',
        ),
        migrations.RemoveIndex(
            model_name='uservocabularyreviewevent',
            name='vocabulary__user_id_c8ea26_idx',
        ),
        migrations.RemoveIndex(
            model_name='userwordprogress',
            name='vocab_user__user_id_fae5a5_idx',
        ),
        migrations.RemoveConstraint(
            model_name='userwordprogress',
            name='uniq_vocab_user_word_progress',
        ),
        migrations.RemoveConstraint(
            model_name='vocabularyword',
            name='uniq_vocab_word_meaning',
        ),
        migrations.RemoveConstraint(
            model_name='word',
            name='uniq_vocab_word_text_language',
        ),
        migrations.AddField(
            model_name='vocabhomework',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vocab_homework_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vocabhomework',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_homeworks', to='classes.assignment'),
        ),
        migrations.AddField(
            model_name='vocabhomework',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_homework', to='classes.classroom'),
        ),
        migrations.AddField(
            model_name='vocabsection',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vocab_sections_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vocabset',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocab_custom_sets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vocabset',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='vocabulary.vocabsection'),
        ),
        migrations.AddField(
            model_name='vocabhomework',
            name='vocab_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homework_links', to='vocabulary.vocabset'),
        ),
        migrations.AddField(
            model_name='vocabsetitem',
            name='vocab_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vocabulary.vocabset'),
        ),
        migrations.AddField(
            model_name='vocabstudysession',
            name='homework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='vocabulary.vocabhomework'),
        ),
        migrations.AddField(
            model_name='vocabstudysession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vocabstudysession',
            name='vocab_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='vocabulary.vocabset'),
        ),
        migrations.AddField(
            model_name='vocabword',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='vocabulary.vocabsection'),
        ),
        migrations.AddField(
            model_name='vocabsetitem',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_items', to='vocabulary.vocabword'),
        ),
        migrations.AddField(
            model_name='vocabwordprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vocabwordprogress',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_rows', to='vocabulary.vocabword'),
        ),
        migrations.RemoveField(
            model_name='reviewlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reviewlog',
            name='word',
        ),
        migrations.RemoveField(
            model_name='uservocabularyprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='uservocabularyprogress',
            name='word',
        ),
        migrations.RemoveField(
            model_name='uservocabularyreviewevent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='uservocabularyreviewevent',
            name='word',
        ),
        migrations.RemoveField(
            model_name='userwordprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userwordprogress',
            name='word',
        ),
        migrations.DeleteModel(
            name='WordDefinition',
        ),
        migrations.AddIndex(
            model_name='vocabset',
            index=models.Index(fields=['owner', '-created_at'], name='vocab_sets_owner_i_28570f_idx'),
        ),
        migrations.AddConstraint(
            model_name='vocabset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner__isnull', True), ('section__isnull', False)), models.Q(('owner__isnull', False), ('section__isnull', True)), _connector='OR'), name='vocab_set_bank_xor_custom'),
        ),
        migrations.AddIndex(
            model_name='vocabhomework',
            index=models.Index(fields=['classroom', 'created_at'], name='vocab_homew_classro_96c874_idx'),
        ),
        migrations.AddConstraint(
            model_name='vocabhomework',
            constraint=models.UniqueConstraint(fields=('assignment', 'vocab_set'), name='uniq_vocab_hw_assignment_set'),
        ),
        migrations.AddIndex(
            model_name='vocabstudysession',
            index=models.Index(fields=['user', 'vocab_set', 'completed_at'], name='vocab_study_user_id_357e6c_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabstudysession',
            index=models.Index(fields=['user', '-started_at'], name='vocab_study_user_id_395c2b_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabword',
            index=models.Index(fields=['section', 'word'], name='vocab_bank__section_ab4a0f_idx'),
        ),
        migrations.AddConstraint(
            model_name='vocabword',
            constraint=models.UniqueConstraint(fields=('section', 'word'), name='uniq_vocab_word_per_section'),
        ),
        migrations.AddConstraint(
            model_name='vocabsetitem',
            constraint=models.UniqueConstraint(fields=('vocab_set', 'word'), name='uniq_vocab_set_word'),
        ),
        migrations.AddIndex(
            model_name='vocabwordprogress',
            index=models.Index(fields=['user', 'status'], name='vocab_progr_user_id_b378c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='vocabwordprogress',
            constraint=models.UniqueConstraint(fields=('user', 'word'), name='uniq_vocab_progress_user_word'),
        ),
        migrations.DeleteModel(
            name='ReviewLog',
        ),
        migrations.DeleteModel(
            name='UserVocabularyProgress',
        ),
        migrations.DeleteModel(
            name='UserVocabularyReviewEvent',
        ),
        migrations.DeleteModel(
            name='VocabularyWord',
        ),
        migrations.DeleteModel(
            name='UserWordProgress',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
