# Generated by Django 6.0.3 on 2026-08-16 05:24
#
# Coverage columns for per-mode vocabulary scoring, plus the index that scoring query
# needs ("the first completed session for this (set, mode)").

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count

BACKFILL_BATCH = 500


def seed_distinct_words(apps, schema_editor):
    """
    Estimate coverage for runs that finished before the column existed.

    Left at 0 these would pay nothing, and homework already assigned and already done
    would go from complete to worthless on the deploy — students being scored on a
    question nobody asked them at the time.

    ``min(total_count, set_size)`` is the best estimate available: nothing recorded WHICH
    words a past run answered. It is exact for matching, speed and test (one answer per
    word) and over-credits only flashcards, which re-drills the missed pile and so reports
    more answers than words. Over-crediting past work is the right direction for an
    estimate students cannot go back and improve.

    COMPLETED sessions only. An unfinished session can still be flushed again, and that
    flush rebuilds ``distinct_words`` from the (empty) ``answered_word_ids`` union — it
    would silently overwrite an estimate here with a smaller real number.
    """
    VocabStudySession = apps.get_model("vocabulary", "VocabStudySession")
    VocabSetItem = apps.get_model("vocabulary", "VocabSetItem")

    sizes = dict(
        VocabSetItem.objects.values("vocab_set_id")
        .order_by()
        .annotate(n=Count("id"))
        .values_list("vocab_set_id", "n")
    )
    if not sizes:
        return

    pending = []
    sessions = VocabStudySession.objects.filter(completed_at__isnull=False).only(
        "id", "vocab_set_id", "total_count", "distinct_words"
    )
    for session in sessions.iterator(chunk_size=BACKFILL_BATCH):
        estimate = min(session.total_count, sizes.get(session.vocab_set_id, 0))
        if estimate <= 0:
            continue
        session.distinct_words = estimate
        pending.append(session)
        if len(pending) >= BACKFILL_BATCH:
            VocabStudySession.objects.bulk_update(pending, ["distinct_words"])
            pending = []
    if pending:
        VocabStudySession.objects.bulk_update(pending, ["distinct_words"])


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0005_vocabhomework_vocabsection_vocabset_vocabsetitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vocabstudysession',
            name='vocab_study_user_id_357e6c_idx',
        ),
        migrations.AddField(
            model_name='vocabstudysession',
            name='answered_word_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vocabstudysession',
            name='distinct_words',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='vocabstudysession',
            index=models.Index(fields=['user', 'vocab_set', 'mode', 'completed_at'], name='vocab_study_user_id_617591_idx'),
        ),
        # Irreversible in one direction only: reversing this migration drops the column
        # the estimate lives in, so there is nothing to undo.
        migrations.RunPython(seed_distinct_words, migrations.RunPython.noop),
    ]
