# Generated by Django 6.0.3 on 2026-07-13 08:22

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0027_assessmentattempt_current_question_index_and_more'),
        ('exams', '0051_mockexam_midterm_level_mockexam_midterm_period_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('ENGLISH', 'English'), ('MATH', 'Math')], db_index=True, max_length=20)),
                ('level', models.CharField(choices=[('foundation', 'Foundation'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], db_index=True, max_length=16)),
                ('title', models.CharField(blank=True, default='', help_text="Optional custom name. Falls back to the derived '<Subject> <Level> Journal'.", max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=12)),
                ('duration_months', models.PositiveSmallIntegerField(default=0)),
                ('total_lessons', models.PositiveSmallIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journals_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journals_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'journals_journal',
                'ordering': ['subject', 'level'],
            },
        ),
        migrations.CreateModel(
            name='JournalLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.PositiveSmallIntegerField(db_index=True)),
                ('lesson_type', models.CharField(choices=[('HOMEWORK', 'Homework'), ('MIDTERM', 'Midterm')], db_index=True, default='HOMEWORK', max_length=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], db_index=True, default='DRAFT', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('instructions', models.TextField(blank=True, default='')),
                ('external_url', models.URLField(blank=True, default='')),
                ('attachment_file', models.FileField(blank=True, null=True, upload_to='journal_files/')),
                ('allow_file_upload', models.BooleanField(default=False)),
                ('practice_scope', models.CharField(choices=[('BOTH', 'Both (English & Math)'), ('ENGLISH', 'English (Reading & Writing) only'), ('MATH', 'Math only')], default='BOTH', max_length=20)),
                ('practice_test_ids', models.JSONField(blank=True, null=True)),
                ('practice_test_pack_ids', models.JSONField(blank=True, null=True)),
                ('category', models.CharField(default='HOMEWORK', max_length=20)),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('due_after_days', models.PositiveSmallIntegerField(blank=True, help_text='Days after the lesson date the homework is due. Null = no deadline.', null=True)),
                ('deadline_time', models.TimeField(blank=True, default=datetime.time(23, 59), help_text='Time of day the homework is due.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='journals.journal')),
                ('midterm_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lessons', to='exams.mockexam')),
            ],
            options={
                'db_table': 'journals_lesson',
                'ordering': ['journal_id', 'lesson_number'],
            },
        ),
        migrations.CreateModel(
            name='JournalAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=40)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_audit_events', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='journals.journal')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='journals.journallesson')),
            ],
            options={
                'db_table': 'journals_audit_event',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalLessonAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_assessment_links', to=settings.AUTH_USER_MODEL)),
                ('assessment_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lesson_links', to='assessments.assessmentset')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='journals.journallesson')),
            ],
            options={
                'db_table': 'journals_lesson_assessment',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JournalLessonAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='journal_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_attachments', to='journals.journallesson')),
            ],
            options={
                'db_table': 'journals_lesson_attachment',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['status'], name='journals_jo_status_607ef2_idx'),
        ),
        migrations.AddConstraint(
            model_name='journal',
            constraint=models.UniqueConstraint(fields=('subject', 'level'), name='uniq_journal_subject_level'),
        ),
        migrations.AddIndex(
            model_name='journallesson',
            index=models.Index(fields=['journal', 'status'], name='journals_le_journal_ab767b_idx'),
        ),
        migrations.AddIndex(
            model_name='journallesson',
            index=models.Index(fields=['journal', 'lesson_type'], name='journals_le_journal_90e47e_idx'),
        ),
        migrations.AddConstraint(
            model_name='journallesson',
            constraint=models.UniqueConstraint(fields=('journal', 'lesson_number'), name='uniq_lesson_number_per_journal'),
        ),
        migrations.AddConstraint(
            model_name='journallessonassessment',
            constraint=models.UniqueConstraint(fields=('lesson', 'assessment_set'), name='uniq_lesson_assessment'),
        ),
    ]
