# Generated by Django 6.0.3 on 2026-07-18 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0029_assessmentset_review_status'),
        ('journals', '0001_initial'),
        ('midterms', '0004_midterm_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journallesson',
            name='deadline_time',
        ),
        migrations.RemoveField(
            model_name='journallesson',
            name='due_after_days',
        ),
        migrations.AddField(
            model_name='journallesson',
            name='midterm_access_days_before',
            field=models.PositiveSmallIntegerField(default=2, help_text='Grant the classroom access to the midterm this many days before the session.'),
        ),
        migrations.AlterField(
            model_name='journallesson',
            name='midterm_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lessons', to='midterms.midterm'),
        ),
        migrations.CreateModel(
            name='JournalClasswork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_review_minutes', models.PositiveSmallIntegerField(default=20)),
                ('new_topic_minutes', models.PositiveSmallIntegerField(default=30)),
                ('break_minutes', models.PositiveSmallIntegerField(default=10)),
                ('exercises_minutes', models.PositiveSmallIntegerField(default=20)),
                ('revision_minutes', models.PositiveSmallIntegerField(default=30)),
                ('new_topic_title', models.CharField(blank=True, default='', max_length=200)),
                ('new_topic_instructions', models.TextField(blank=True, default='')),
                ('new_topic_external_url', models.URLField(blank=True, default='')),
                ('new_topic_attachment_file', models.FileField(blank=True, null=True, upload_to='journal_files/')),
                ('new_topic_practice_test_ids', models.JSONField(blank=True, null=True)),
                ('new_topic_practice_test_pack_ids', models.JSONField(blank=True, null=True)),
                ('exercise_practice_test_ids', models.JSONField(blank=True, null=True)),
                ('exercise_practice_test_pack_ids', models.JSONField(blank=True, null=True)),
                ('revision_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classwork', to='journals.journallesson')),
            ],
            options={
                'db_table': 'journals_classwork',
            },
        ),
        migrations.CreateModel(
            name='JournalClassworkAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='journal_files/')),
                ('block', models.CharField(choices=[('NEW_TOPIC', 'New topic'), ('EXERCISES', 'Exercises')], default='NEW_TOPIC', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_attachments', to='journals.journalclasswork')),
            ],
            options={
                'db_table': 'journals_classwork_attachment',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JournalClassworkAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(choices=[('NEW_TOPIC', 'New topic'), ('EXERCISES', 'Exercises')], db_index=True, default='NEW_TOPIC', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_classwork_assessment_links', to=settings.AUTH_USER_MODEL)),
                ('assessment_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_classwork_links', to='assessments.assessmentset')),
                ('classwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='journals.journalclasswork')),
            ],
            options={
                'db_table': 'journals_classwork_assessment',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('classwork', 'assessment_set', 'block'), name='uniq_classwork_assessment_block')],
            },
        ),
    ]
