# Generated by Django 6.0.3 on 2026-07-19 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0033_midtermschedule_access_code_and_more'),
        ('journals', '0003_backfill_classwork'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('bound_at', models.DateTimeField(auto_now_add=True)),
                ('bound_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_bindings', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal_binding', to='classes.classroom')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classroom_bindings', to='journals.journal')),
            ],
            options={
                'db_table': 'journals_classroom_journal',
            },
        ),
        migrations.CreateModel(
            name='ClassroomLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.PositiveSmallIntegerField()),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('homework_released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_deliveries', to='classes.assignment')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_lessons', to='classes.classroom')),
                ('journal_lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classroom_deliveries', to='journals.journallesson')),
                ('midterm_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_deliveries', to='classes.midtermschedule')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lesson_releases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'journals_classroom_lesson',
                'ordering': ['classroom_id', 'lesson_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomLessonGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(choices=[('HOMEWORK', 'Homework'), ('NEW_TOPIC', 'New topic'), ('EXERCISES', 'Exercises'), ('MIDTERM', 'Midterm')], db_index=True, max_length=16)),
                ('resource_type', models.CharField(db_index=True, max_length=32)),
                ('resource_id', models.PositiveIntegerField()),
                ('granted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('classroom_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='journals.classroomlesson')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lesson_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'journals_classroom_lesson_grant',
                'ordering': ['-granted_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='classroomlesson',
            index=models.Index(fields=['classroom', 'lesson_number'], name='journals_cl_classro_4f315c_idx'),
        ),
        migrations.AddConstraint(
            model_name='classroomlesson',
            constraint=models.UniqueConstraint(fields=('classroom', 'journal_lesson'), name='journals_classroom_lesson_unique'),
        ),
        migrations.AddConstraint(
            model_name='classroomlessongrant',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('classroom_lesson', 'block', 'resource_type', 'resource_id'), name='journals_classroom_lesson_grant_unique_active'),
        ),
    ]
