# Generated by Django 6.0.3 on 2026-07-19 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0033_midtermschedule_access_code_and_more'),
        ('journals', '0004_classroomjournal_classroomlesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomlesson',
            name='classwork_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_classwork_deliveries', to='classes.assignment'),
        ),
    ]
