# Generated by Django 6.0.3 on 2026-07-19 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0005_classroomlesson_classwork_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomlesson',
            name='journal_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_deliveries', to='journals.journallesson'),
        ),
    ]
