# Generated by Django 6.0.3 on 2026-07-26 06:37

from django.db import migrations, models


def seed_lists_from_single(apps, schema_editor):
    """Copy each existing single link into its new list field."""
    JournalLesson = apps.get_model('journals', 'JournalLesson')
    for pk, url in JournalLesson.objects.exclude(external_url='').values_list('id', 'external_url'):
        if url:
            JournalLesson.objects.filter(pk=pk).update(external_urls=[url])

    JournalClasswork = apps.get_model('journals', 'JournalClasswork')
    for pk, url in JournalClasswork.objects.exclude(new_topic_external_url='').values_list(
        'id', 'new_topic_external_url'
    ):
        if url:
            JournalClasswork.objects.filter(pk=pk).update(new_topic_external_urls=[url])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0007_repair_midterm_exam_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalclasswork',
            name='new_topic_external_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='journallesson',
            name='external_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(seed_lists_from_single, noop),
    ]
