# Generated by Django 6.0.3 on 2026-07-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0008_journalclasswork_new_topic_external_urls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalclasswork',
            name='new_topic_video_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='journallesson',
            name='video_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
