# Generated by Django 6.0.3 on 2026-07-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0009_journalclasswork_new_topic_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalclasswork',
            name='new_topic_video_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='journal_videos/'),
        ),
        migrations.AddField(
            model_name='journallesson',
            name='video_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='journal_videos/'),
        ),
    ]
