# Generated by Django 6.0.3 on 2026-07-31 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0010_journalclasswork_new_topic_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalclasswork',
            name='exercise_vocabulary_set_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalclasswork',
            name='new_topic_vocabulary_set_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journallesson',
            name='vocabulary_set_ids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
