# Generated by Django 6.0.3 on 2026-08-29 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0011_journalclasswork_exercise_vocabulary_set_ids_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('summary', models.CharField(blank=True, default='', max_length=300)),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=0)),
                ('require_read_confirmation', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap', to='journals.journallesson')),
            ],
            options={
                'db_table': 'journals_roadmap',
            },
        ),
        migrations.CreateModel(
            name='JournalRoadmapSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('kind', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video')], default='TEXT', max_length=8)),
                ('heading', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='journal_roadmap/')),
                ('caption', models.CharField(blank=True, default='', max_length=300)),
                ('video_url', models.URLField(blank=True, default='', max_length=500)),
                ('video_file', models.FileField(blank=True, max_length=500, null=True, upload_to='journal_roadmap_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='journals.journalroadmap')),
            ],
            options={
                'db_table': 'journals_roadmap_section',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['roadmap', 'order'], name='journals_ro_roadmap_2aca9b_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoadmapRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('classroom_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_reads', to='journals.classroomlesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'journals_roadmap_read',
                'ordering': ['-read_at', '-id'],
                'indexes': [models.Index(fields=['student', 'classroom_lesson'], name='journals_ro_student_26798b_idx')],
                'constraints': [models.UniqueConstraint(fields=('classroom_lesson', 'student'), name='uniq_roadmap_read_per_student')],
            },
        ),
    ]
