# Generated by Django 6.0.3 on 2026-09-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0012_journalroadmap_journalroadmapsection_roadmapread'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalclasswork',
            name='new_topic_external_url_labels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='journallesson',
            name='external_url_labels',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
