# Generated by Django 6.0.3 on 2026-06-26 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0024_drop_pastpaperpack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroommaterial',
            name='file',
            field=models.FileField(upload_to='classroom_materials/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'rtf', 'txt', 'ppt', 'pptx', 'key', 'odp', 'xls', 'xlsx', 'csv', 'mp3', 'm4a', 'wav', 'aac', 'ogg', 'png', 'jpg', 'jpeg'])]),
        ),
    ]
