# Generated by Django 6.0.3 on 2026-07-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0025_alter_classroommaterial_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='practice_test_pack_ids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
