# Generated by Django 6.0.3 on 2026-07-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0026_assignment_practice_test_pack_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='allow_file_upload',
            field=models.BooleanField(default=False),
        ),
    ]
