# Generated by Django 6.0.3 on 2026-07-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0028_backfill_allow_file_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='level',
            field=models.CharField(blank=True, choices=[('foundation', 'Foundation'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], db_index=True, default='', max_length=16),
        ),
    ]
