# Generated by Django 6.0.3 on 2026-07-07 15:45

import classes.models_certificates
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0029_classroom_level'),
        ('exams', '0049_mockexam_midterm_module_question_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MidtermCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('midterm_title', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, max_length=32)),
                ('score', models.IntegerField()),
                ('scoring_scale', models.CharField(blank=True, max_length=16)),
                ('rank', models.PositiveIntegerField()),
                ('cohort_size', models.PositiveIntegerField()),
                ('code', models.CharField(db_index=True, default=classes.models_certificates._new_code, max_length=32, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exams.testattempt')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midterm_certificates', to='classes.classroom')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mock_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midterm_certificates', to='exams.mockexam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midterm_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'classroom_midterm_certificates',
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['mock_exam', 'student'], name='classroom_m_mock_ex_d11ab2_idx'), models.Index(fields=['classroom', 'mock_exam'], name='classroom_m_classro_3caff6_idx')],
                'constraints': [models.UniqueConstraint(fields=('classroom', 'mock_exam', 'student'), name='uniq_midterm_certificate_per_student')],
            },
        ),
        migrations.CreateModel(
            name='MidtermSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('ignore_start', models.BooleanField(default=False, help_text='Teacher override: open immediately, ignoring starts_at.')),
                ('results_released', models.BooleanField(db_index=True, default=False)),
                ('results_released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midterm_schedules', to='classes.classroom')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mock_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midterm_schedules', to='exams.mockexam')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'classroom_midterm_schedules',
                'indexes': [models.Index(fields=['mock_exam', 'classroom'], name='classroom_m_mock_ex_f2b228_idx')],
                'constraints': [models.UniqueConstraint(fields=('classroom', 'mock_exam'), name='uniq_midterm_schedule_per_classroom')],
            },
        ),
    ]
