# Generated by Django 6.0.3 on 2026-07-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0030_midtermcertificate_midtermschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='midtermcertificate',
            name='issued_by_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
