# Generated by Django 6.0.3 on 2026-07-08 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0031_midtermcertificate_issued_by_name'),
        ('exams', '0050_alter_module_practice_test'),
        ('midterms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='midtermcertificate',
            options={'ordering': [models.OrderBy(models.F('rank'), nulls_last=True), 'flavor']},
        ),
        migrations.AddField(
            model_name='midtermcertificate',
            name='flavor',
            field=models.CharField(choices=[('CLASSROOM', 'Classroom'), ('STANDALONE', 'Standalone')], db_index=True, default='CLASSROOM', max_length=16),
        ),
        migrations.AddField(
            model_name='midtermcertificate',
            name='midterm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='midterms.midterm'),
        ),
        migrations.AddField(
            model_name='midtermcertificate',
            name='midterm_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='midterms.midtermattempt'),
        ),
        migrations.AddField(
            model_name='midtermschedule',
            name='midterm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='midterms.midterm'),
        ),
        migrations.AlterField(
            model_name='midtermcertificate',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='midterm_certificates', to='classes.classroom'),
        ),
        migrations.AlterField(
            model_name='midtermcertificate',
            name='cohort_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='midtermcertificate',
            name='mock_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='midterm_certificates', to='exams.mockexam'),
        ),
        migrations.AlterField(
            model_name='midtermcertificate',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='midtermschedule',
            name='mock_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='midterm_schedules', to='exams.mockexam'),
        ),
        migrations.AddIndex(
            model_name='midtermcertificate',
            index=models.Index(fields=['midterm', 'student'], name='classroom_m_midterm_f70e87_idx'),
        ),
        migrations.AddIndex(
            model_name='midtermschedule',
            index=models.Index(fields=['midterm', 'classroom'], name='classroom_m_midterm_bb5d07_idx'),
        ),
        migrations.AddConstraint(
            model_name='midtermcertificate',
            constraint=models.UniqueConstraint(condition=models.Q(('flavor', 'CLASSROOM')), fields=('classroom', 'midterm', 'student'), name='uniq_midterm_cert_classroom'),
        ),
        migrations.AddConstraint(
            model_name='midtermcertificate',
            constraint=models.UniqueConstraint(condition=models.Q(('flavor', 'STANDALONE')), fields=('midterm', 'student'), name='uniq_midterm_cert_standalone'),
        ),
        migrations.AddConstraint(
            model_name='midtermschedule',
            constraint=models.UniqueConstraint(fields=('classroom', 'midterm'), name='uniq_midterm_schedule_per_classroom_v2'),
        ),
    ]
