# Generated by Django 6.0.3 on 2026-07-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0032_alter_midtermcertificate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='midtermschedule',
            name='access_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='midtermschedule',
            name='access_code_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
