# Generated by Django 6.0.3 on 2026-07-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0033_midtermschedule_access_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='midtermschedule',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
