# Generated by Django 6.0.3 on 2026-07-26 06:37

from django.db import migrations, models


def seed_list_from_single(apps, schema_editor):
    """Copy each existing single ``external_url`` into the new ``external_urls`` list."""
    Assignment = apps.get_model('classes', 'Assignment')
    for pk, url in Assignment.objects.exclude(external_url='').values_list('id', 'external_url'):
        if url:
            Assignment.objects.filter(pk=pk).update(external_urls=[url])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0034_midtermschedule_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='external_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(seed_list_from_single, noop),
    ]
