# Generated by Django 6.0.3 on 2026-07-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0035_assignment_external_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
