# Generated by Django 6.0.3 on 2026-07-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0036_assignment_notified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingsnapshot',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
