# Generated by Django 6.0.3 on 2026-07-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0037_alter_rankingsnapshot_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='video_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
