# Generated by Django 6.0.3 on 2026-07-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0038_assignment_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='video_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='homework_videos/'),
        ),
    ]
