# Generated by Django 6.0.3 on 2026-08-07 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0040_attendance_session_unique_per_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField()),
                ('capacity', models.PositiveSmallIntegerField(default=1)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('is_cancelled', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('support_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_availability', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_availability',
                'ordering': ['starts_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupportBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, help_text='What the student needs help with.', max_length=240)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('HELD', 'Held'), ('NO_SHOW', 'Did not attend'), ('CANCELLED', 'Cancelled')], db_index=True, default='BOOKED', max_length=10)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='classes.supportavailability')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_bookings', to='classes.classroom')),
                ('settled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_bookings',
                'ordering': ['-booked_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='supportavailability',
            index=models.Index(fields=['support_teacher', 'starts_at'], name='support_ava_support_bf1817_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportavailability',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='support_availability_ends_after_start'),
        ),
        migrations.AddConstraint(
            model_name='supportavailability',
            constraint=models.UniqueConstraint(fields=('support_teacher', 'starts_at'), name='uniq_support_slot_per_teacher_start'),
        ),
        migrations.AddIndex(
            model_name='supportbooking',
            index=models.Index(fields=['student', 'status'], name='support_boo_student_437e37_idx'),
        ),
        migrations.AddIndex(
            model_name='supportbooking',
            index=models.Index(fields=['availability', 'status'], name='support_boo_availab_f471db_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportbooking',
            constraint=models.UniqueConstraint(fields=('availability', 'student'), name='uniq_support_booking_per_slot'),
        ),
    ]
