# Generated by Django 6.0.3 on 2026-08-14 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0042_support_cancel_reason_and_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, default='', max_length=16)),
                ('address', models.CharField(blank=True, default='', max_length=240)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'org_branches',
                'ordering': ['region__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(blank=True, default='', help_text='Optional short label for filter chips, e.g. TAS.', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'org_regions',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The site this class meets at. Students inherit their branch from it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='classes.branch'),
        ),
        migrations.AddField(
            model_name='branch',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='classes.region'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('region', 'name'), name='uniq_branch_name_per_region'),
        ),
    ]
