# Generated by Django 6.0.3 on 2026-08-14 19:31

import classes.models_certificates
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0043_branch_region_classroom_branch_branch_region_and_more'),
        ('exams', '0054_mockexam_midterm_two_module_runtime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PastpaperCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('paper_title', models.CharField(max_length=200)),
                ('collection_name', models.CharField(blank=True, default='', max_length=200)),
                ('subject', models.CharField(blank=True, max_length=32)),
                ('score', models.IntegerField()),
                ('questions_total', models.PositiveIntegerField(default=0)),
                ('questions_correct', models.PositiveIntegerField(default=0)),
                ('code', models.CharField(db_index=True, default=classes.models_certificates._new_code, max_length=32, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='exams.testattempt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastpaper_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pastpaper_certificates',
                'ordering': ['-issued_at', '-id'],
                'indexes': [models.Index(fields=['student', '-issued_at'], name='pastpaper_c_student_34a2ef_idx')],
                'constraints': [models.UniqueConstraint(fields=('attempt',), name='uniq_pastpaper_cert_per_attempt')],
            },
        ),
    ]
