# Generated by Django 6.0.3 on 2026-08-24 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0045_supportbooking_invited_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], db_index=True)),
                ('is_working', models.BooleanField(default=True)),
                ('start_hour', models.PositiveSmallIntegerField(default=8)),
                ('end_hour', models.PositiveSmallIntegerField(default=18, help_text='Exclusive.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('support_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_working_hours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'support working hours',
                'db_table': 'support_working_hours',
                'ordering': ['support_teacher_id', 'weekday'],
                'constraints': [models.UniqueConstraint(fields=('support_teacher', 'weekday'), name='uniq_support_working_day_per_teacher'), models.CheckConstraint(condition=models.Q(('end_hour__gt', models.F('start_hour'))), name='support_working_hours_end_after_start'), models.CheckConstraint(condition=models.Q(('start_hour__gte', 0), ('start_hour__lte', 23)), name='support_working_hours_start_in_day'), models.CheckConstraint(condition=models.Q(('end_hour__gte', 1), ('end_hour__lte', 24)), name='support_working_hours_end_in_day')],
            },
        ),
    ]
