# Generated by Django 6.0.3 on 2026-08-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0046_supportworkinghours'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='telegram_group_url',
            field=models.URLField(blank=True, default='', help_text='Invite link for the class Telegram group, e.g. https://t.me/joinchat/…', max_length=300),
        ),
    ]
