# Generated by Django 6.0.3 on 2026-08-30 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0047_classroom_telegram_group_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomMembershipEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_name', models.CharField(blank=True, max_length=200)),
                ('student_name', models.CharField(blank=True, max_length=200)),
                ('actor_name', models.CharField(blank=True, max_length=200)),
                ('action', models.CharField(choices=[('ADDED', 'Added to the class'), ('REMOVED', 'Removed from the class'), ('REINSTATED', 'Put back in the class'), ('ROLE_CHANGED', 'Role changed'), ('STATUS_CHANGED', 'Status changed'), ('DELETED', 'Membership row deleted')], db_index=True, max_length=16)),
                ('previous_role', models.CharField(blank=True, max_length=10)),
                ('new_role', models.CharField(blank=True, max_length=10)),
                ('previous_status', models.CharField(blank=True, max_length=10)),
                ('new_status', models.CharField(blank=True, max_length=10)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_events_authored', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_events', to='classes.classroom')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'classroom_membership_events',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['classroom', '-created_at'], name='cme_classroom_created'), models.Index(fields=['student', '-created_at'], name='cme_student_created'), models.Index(fields=['actor', '-created_at'], name='cme_actor_created')],
            },
        ),
    ]
