# Generated by Django 6.0.3 on 2026-09-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0048_classroommembershipevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='external_url_labels',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
