# Generated by Django 6.0.3 on 2026-09-04 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0049_external_url_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomTelegramEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_name', models.CharField(blank=True, default='', max_length=200)),
                ('user_name', models.CharField(blank=True, default='', max_length=200)),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('LINK_ISSUED', 'One-time invite link issued'), ('JOINED', 'Joined the group'), ('JOIN_REJECTED', 'Join rejected and removed'), ('REMOVED', 'Removed from the group'), ('LEFT', 'Left the group'), ('RECONCILED', 'State corrected by the sweep'), ('UNMANAGED_JOIN', 'Unrecognised account joined'), ('CONFIG_ERROR', 'Group is misconfigured')], db_index=True, max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=24)),
                ('detail', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_events', to='classes.classroom')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_telegram_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'classroom_telegram_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomTelegramMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('telegram_username', models.CharField(blank=True, default='', max_length=64)),
                ('telegram_display_name', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Invite issued'), ('JOINED', 'In the group'), ('LEFT', 'Left the group'), ('REMOVED', 'Removed from the group')], db_index=True, default='PENDING', max_length=10)),
                ('invite_link', models.CharField(blank=True, db_index=True, default='', max_length=300)),
                ('invite_expires_at', models.DateTimeField(blank=True, null=True)),
                ('invite_issued_at', models.DateTimeField(blank=True, null=True)),
                ('invite_issued_count', models.PositiveIntegerField(default=0)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('removed_reason', models.CharField(blank=True, choices=[('FROZEN', 'Account frozen on the site'), ('NOT_IN_CLASS', 'No longer a member of the class'), ('IDENTITY_MISMATCH', 'Joined with a different Telegram account'), ('MANUAL', 'Removed by staff')], default='', max_length=24)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_members', to='classes.classroom')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_telegram_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'classroom_telegram_members',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('classroom', 'user'), name='uniq_classroom_telegram_member_user'), models.UniqueConstraint(condition=models.Q(('telegram_user_id__isnull', False)), fields=('classroom', 'telegram_user_id'), name='uniq_classroom_telegram_member_tg')],
            },
        ),
    ]
