# Generated by Django 6.0.3 on 2026-09-24 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0052_telegramstarttoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='manual_grade_weight_percent',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Percent of the grade the teacher marks by hand (0-100). Blank = the grade comes entirely from the auto-graded parts.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
