# Generated by Django 6.0.3 on 2026-07-18 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_email_verification_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_email', models.EmailField(db_index=True, help_text='Normalized (lowercased).', max_length=254)),
                ('code_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('expired', 'Expired'), ('burned', 'Burned'), ('refused', 'Refused')], db_index=True, default='pending', max_length=16)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_email_claims',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'status', '-created_at'], name='users_email_user_id_052da5_idx'), models.Index(fields=['target_email', 'status'], name='users_email_target__b56b33_idx')],
            },
        ),
    ]
