# Generated by Django 6.0.3 on 2026-08-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_email_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('support_teacher', 'Support teacher'), ('test_admin', 'Test admin'), ('test_auditor', 'Test auditor'), ('admin', 'Admin'), ('super_admin', 'Super admin')], db_index=True, default='student', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='subject',
            field=models.CharField(blank=True, choices=[('math', 'Math'), ('english', 'English')], db_index=True, help_text='Required for **teacher** and **support_teacher** (math or english). Must be null for admin, test_admin, test_auditor, super_admin, and students.', max_length=16, null=True),
        ),
    ]
