# Generated by Django 6.0.3 on 2026-08-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_user_role_alter_user_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subject',
            field=models.CharField(blank=True, choices=[('math', 'Math'), ('english', 'English'), ('both', 'Both (support only)')], db_index=True, help_text='Required for **teacher** (math or english) and **support_teacher** (math, english, or both). Must be null for admin, test_admin, test_auditor, super_admin, and students.', max_length=16, null=True),
        ),
    ]
