# Generated by Django 6.0.3 on 2026-09-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_user_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_bot_user_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Telegram Bot API user id, learned when this person opens the bot from their own /start link.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='OIDC subject from Telegram sign-in. NOT the Bot API user id — see telegram_bot_user_id.', null=True, unique=True),
        ),
    ]
