# Generated by Django 6.0.3 on 2026-07-08 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0050_alter_module_practice_test'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('break_minutes', models.PositiveSmallIntegerField(default=10, help_text='Break between English and Math.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mocks_mock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MockAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_answers', models.JSONField(blank=True, default=dict)),
                ('flagged', models.JSONField(blank=True, default=dict)),
                ('phase_started_at', models.JSONField(blank=True, default=dict)),
                ('current_state', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('ENGLISH_M1_ACTIVE', 'English module 1'), ('ENGLISH_M2_ACTIVE', 'English module 2'), ('BREAK', 'Break'), ('MATH_M1_ACTIVE', 'Math module 1'), ('MATH_M2_ACTIVE', 'Math module 2'), ('SCORING', 'Scoring'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], db_index=True, default='NOT_STARTED', max_length=24)),
                ('version_number', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('english_score', models.IntegerField(blank=True, null=True)),
                ('math_score', models.IntegerField(blank=True, null=True)),
                ('total_score', models.IntegerField(blank=True, null=True)),
                ('scoring_started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('mock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mocks.mock')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mocks_attempt',
            },
        ),
        migrations.CreateModel(
            name='MockAttemptIdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(db_index=True, max_length=64)),
                ('key', models.CharField(db_index=True, max_length=128)),
                ('response_status', models.PositiveSmallIntegerField(default=200)),
                ('response_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to='mocks.mockattempt')),
            ],
            options={
                'db_table': 'mocks_attempt_idempotency_keys',
            },
        ),
        migrations.CreateModel(
            name='MockSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(choices=[('READING_WRITING', 'Reading & Writing'), ('MATH', 'Math')], db_index=True, max_length=20)),
                ('mock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='mocks.mock')),
                ('module1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='exams.module')),
                ('module2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='exams.module')),
            ],
            options={
                'db_table': 'mocks_section',
            },
        ),
        migrations.AddIndex(
            model_name='mockattempt',
            index=models.Index(fields=['mock', 'student'], name='mocks_attem_mock_id_03c913_idx'),
        ),
        migrations.AddIndex(
            model_name='mockattempt',
            index=models.Index(fields=['current_state'], name='mocks_attem_current_85c5b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='mockattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('is_completed', False), models.Q(('current_state', 'ABANDONED'), _negated=True)), fields=('student', 'mock'), name='uniq_active_mock_attempt_per_student'),
        ),
        migrations.AddConstraint(
            model_name='mockattemptidempotencykey',
            constraint=models.UniqueConstraint(fields=('attempt', 'endpoint', 'key'), name='uniq_mock_attempt_endpoint_key'),
        ),
        migrations.AddConstraint(
            model_name='mocksection',
            constraint=models.UniqueConstraint(fields=('mock', 'subject'), name='uniq_mock_section_per_subject'),
        ),
    ]
