# Generated by Django 6.0.3 on 2026-08-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockattempt',
            name='pause_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockattempt',
            name='paused_seconds',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
