# Generated by Django 6.0.3 on 2026-08-02 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0039_assignment_video_file'),
        ('mocks', '0002_mockattempt_pause_started_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('session_date', models.DateField(db_index=True)),
                ('access_code', models.CharField(blank=True, db_index=True, default='', max_length=6)),
                ('access_code_set_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open for requests'), ('STARTED', 'Started'), ('ENDED', 'Ended'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mocks_session',
                'ordering': ['-session_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MockSessionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Waiting for approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mocks_session_participant',
                'ordering': ['requested_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='mockattempt',
            name='uniq_active_mock_attempt_per_student',
        ),
        migrations.AddField(
            model_name='mockattempt',
            name='offscreen_violations',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mockattempt',
            name='terminated_reason',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='mocksession',
            name='classroom',
            field=models.ForeignKey(blank=True, help_text='Which room runs it. Blank = any teacher on the platform may run it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_sessions', to='classes.classroom'),
        ),
        migrations.AddField(
            model_name='mocksession',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mocksession',
            name='mock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='mocks.mock'),
        ),
        migrations.AddField(
            model_name='mocksession',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mockattempt',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mocks.mocksession'),
        ),
        migrations.AddIndex(
            model_name='mockattempt',
            index=models.Index(fields=['session', 'current_state'], name='mocks_attem_session_493d04_idx'),
        ),
        migrations.AddConstraint(
            model_name='mockattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('is_completed', False), ('session__isnull', True), models.Q(('current_state', 'ABANDONED'), _negated=True)), fields=('student', 'mock'), name='uniq_active_solo_mock_attempt'),
        ),
        migrations.AddConstraint(
            model_name='mockattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('session__isnull', False)), fields=('student', 'session'), name='uniq_mock_attempt_per_session'),
        ),
        migrations.AddField(
            model_name='mocksessionparticipant',
            name='attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mocks.mockattempt'),
        ),
        migrations.AddField(
            model_name='mocksessionparticipant',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mocksessionparticipant',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='mocks.mocksession'),
        ),
        migrations.AddField(
            model_name='mocksessionparticipant',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_session_places', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='mockattempt',
            name='pause_started_at',
        ),
        migrations.RemoveField(
            model_name='mockattempt',
            name='paused_seconds',
        ),
        migrations.AddIndex(
            model_name='mocksession',
            index=models.Index(fields=['access_code', 'session_date'], name='mocks_sessi_access__a2168c_idx'),
        ),
        migrations.AddIndex(
            model_name='mocksession',
            index=models.Index(fields=['status', 'session_date'], name='mocks_sessi_status_2eab1b_idx'),
        ),
        migrations.AddIndex(
            model_name='mocksessionparticipant',
            index=models.Index(fields=['session', 'status'], name='mocks_sessi_session_93cf65_idx'),
        ),
        migrations.AddConstraint(
            model_name='mocksessionparticipant',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='uniq_mock_session_place'),
        ),
    ]
